src/events/Message.ts, src/programs/Unassigned.ts, src/programs/index.ts
Adds a command that both adds the Unassigned role to all members without *any* role (other than everyone) and clears it from members who still have it despite having other roles already.
=> Unassigned command

src/programs/Ticket.ts
.cache was removed in several occassions in the last commit on this file which led to the bot breaking on !shoutout and !fiyesta
=> Readded .cache

src/events/MessageManager.ts
Adds the entire hobbies category to channels `@group` can be used in.
=> feat: more channels at group can be used in

src/events/ReactionRemove.ts
=> feat: delete permissions instead of unsetting them (closes #40)

src/programs/BuddyProject.ts
will automatically allow the user to see the name as an @name instead of just a number  like 219502124709445633
=> auto @names

src/events/MessageManager.ts, src/programs/PhilosophyManager.ts, src/programs/index.ts
This branch adds the ability for users to get the current topic with `!topic`
=> Philosophy: Get Topic

src/programs/WhereAreYouFromManager.spec.ts, src/programs/WhereAreYouFromManager.ts
This PR fixes two issues with Oman and Romania in where are you from:
- The flag of Oman got the user the role for Romania
- Typing out Romania got two found country entries (Romania and Oman) because of the way how countries are checked.
=> Fixes for Oman - Romania issues

src/events/MemberLeave.ts, src/index.ts, src/programs/BuddyProjectGhost.ts, src/programs/BuddyProjectManager.ts
Remove the member from as many DB as possible
Let me know if I missed any DBs
=> Feat: MemberLeave

src/programs/BuddyProjectGhost.ts
=> feat: only wait 3 days instead of 7

src/programs/BuddyProjectGhost.ts
This is a little weird sight :')
=> fix: Round remaining time

src/collections/flagEmojis.ts, src/programs/WhereAreYouFromManager.spec.ts, src/programs/WhereAreYouFromManager.ts
This fixes a few of the cases that mass pinged supports in bot-output. Test-cases were added for them.
=> fix: uae, england, scotland flags in flag-drop

src/programs/BuddyProject.ts
See https://discordapp.com/channels/449984633342525462/450642946556166145/728996512457162794
=> fix: buddy message (mention !buddy)

src/programs/GroupManager.ts
This PR adds a few updates to how `!group join` and `!group leave` are handled.
Main feature is the ability to join/leave multiple groups at once by using spaces/commas as seperators. As consequence to the option of passing multiple arguments, there are a few changes to how empty arguments are responded to. With only one argument passed, the handling *should* remain pretty much the same compared to how they are now.
=> feat: allow joining/leaving multiple groups at once

src/events/GuildMemberUpdate.ts, src/programs/Seperators.ts
=> feat: automatic seperator roles

src/events/MessageManager.ts, src/programs/VoiceOnDemand.ts
You can now select an emoji for your private voice channel (from a small, preselect pool of options).
=> !voice channel emoji selection

src/programs/TopicManager.ts
=> changed philosophy questions

src/events/GuildMemberUpdate.ts
=> lets supports have nitro colours

.gitignore, .vscode/settings.json, src/programs/Someone.ts
included regex to prevent @s from being parsed in argument.
=> at-someone abuse fix

src/collections/flagEmojis.ts
changed 4 region names so mods dont get pinged that the role doesn't exist when it does. can update list over time
=> added syria, palestine, BIOT, SM as selectable roles

src/events/MessageManager.ts, src/events/Ready.ts, src/programs/DailyChallenge.ts, src/programs/GroupManager.ts, src/programs/index.ts
Refactors DailyChallenge:
- Rename SendFromDB.ts to DailyChallenge.ts
- Move initialization to DailyChallenge.ts
- Add some awaits
Fix #202:
- The bot checks every 24 hours whether to post or not
=> chore: refactor daily challenge, fix: #202

src/events/MessageManager.ts
=> feat: use whitelisted roles for the mass ping trigger

src/programs/VoiceOnDemand.ts
Let people know what's going on in the room
=> Add useful emojis

src/programs/VoiceOnDemand.ts
The joystick had a weird icon when room gets created and it's hard to see what it is. Looked like a dildo to me.
A dice should improve visibility and understanding, especially in discord dark mode.
=> Change Joystick with Dice

.gitignore, CONTRIBUTING.md
This PR makes changes to the README.md to include information on how to authenticate against the GitHub Package Registry to install `@yes-theory-fam/database`.
=> chore: update README

.gitignore, .renovaterc.json, package-lock.json, package.json
- renovate group prisma
- remove typeorm dependencies
=> update renovate config

.github/workflows/ci.yml, .gitignore, .npmrc.example, CONTRIBUTING.md, __tests__/event-distribution/events/events.spec.ts, __tests__/mocks/index.ts, jest.config.js, package-lock.json, package.json, src/event-distribution/command-decorator.ts, src/event-distribution/event-distribution.ts, src/event-distribution/events/events.ts, src/event-distribution/types/base.ts, src/event-distribution/types/handler.ts, src/event-distribution/types/hioc.ts
Introduce jest tests with 2 first tests.
Add Testing in pipline
closes #235
=> Introduce tests with jest

src/programs/voice-on-demand.ts
There was a false. Instead of `@username` it was `<@@username>`
getting the ID should fix this.
=> fix bug with false mentions

__tests__/event-distribution/events/__snapshots__/events.spec.ts.snap, __tests__/event-distribution/events/__snapshots__/message.spec.ts.snap, __tests__/event-distribution/events/events.spec.ts, __tests__/event-distribution/events/message.spec.ts, __tests__/mocks/index.ts
Add test for `extractMessageInfo()` in message.ts from event_distribution
=> add test for extractMessageInfo

src/programs/where-are-you-from.ts
edit the bot welcome DM to include the !menu command
=> update the bot welcome DM

src/programs/where-are-you-from.ts
A premature LGTM on my end introduced a syntax error. This PR fixes that by escaping the backquotes causing issues.
=> fix: syntax error

__tests__/utils/country-role-finder.spec.ts, src/utils/country-role-finder.ts
Addresses https://github.com/Yes-Theory-Fam/yesbot-ts/pull/299#discussion_r658131187 and simplifies the check by a bit to cover more possible cases.
=> Simplify the country role finder

.env.example, __tests__/mocks/index.ts, __tests__/utils/country-role-finder.spec.ts, environment.d.ts, src/common/moderator.ts, src/programs/birthday-manager.ts, src/programs/map.ts, src/programs/profile.ts, src/programs/where-are-you-from.ts, src/scripts/export-region-members.ts, src/scripts/member-migration.ts, src/utils/country-role-finder.ts
New way of checking the country role
=> transition for new country roles

src/programs/where-are-you-from.ts, src/utils/country-role-finder.ts
This PR fixes yet another issue with roles not being picked up correctly due to the emojis.
=> fix: reaction to regional assignment

.renovaterc.json
this should update all node versions at the same time.
=> add node update config to renovate

.github/workflows/build.yml, .github/workflows/linting.yml, .github/workflows/test.yml
Refactored Pipeline so they can run in parallel. In this I added a better solution to download the @Yes-Theory-Fam packages without manually write the file.
Added Pipeline to Build and publish a Docker image on release.
=> ci(Deploy Dockerimage): Refactor Pipeline and add Job to publish Pipeline

__tests__/programs/birthday-manager.spec.ts, __tests__/programs/where-are-you-from-manager.spec.ts
a26f657 deleted some test files. This PR adds them back.
=> Restore deleted tests

src/common/interfaces.ts, src/common/moderator.ts, src/common/tools.ts, src/event-distribution/events/events.ts, src/events/guild-member-update.ts, src/events/message.ts, src/events/reaction-add.ts, src/games/README.md, src/games/game-configurator.ts, src/games/game-hub.ts, src/games/game-session.ts, src/games/spyfall/spyfall.ts, src/programs/birthday-manager.ts, src/programs/index.ts, src/programs/nitro-colors.ts, src/programs/react-role.ts, src/programs/topics.ts, src/programs/voice-on-demand.ts, src/programs/where-are-you-from.ts, src/scripts/member-migration.ts, src/utils/country-role-finder.ts
use intelliJ Code fromatting tool
=> refactor(imports): optimize imports

__tests__/event-distribution/events/events.spec.ts, src/event-distribution/command-decorator.ts, src/event-distribution/event-distribution.ts, src/event-distribution/events/events.ts, src/event-distribution/events/ready.ts, src/event-distribution/types/base.ts, src/index.ts, src/programs/decorator-test.ts
This PR adds support for the ready event to the new event distribution system. It also adds a few tests that were forgotten in an earlier PR.
- feat: Add GuildMemberUpdate to event distribution
- feat: Ready event in event distribution
=> feat: ready event

src/programs/map.ts, src/programs/where-are-you-from.ts
After DMs have been enabled on YesBot again, this PR re-enables the two features that had been disabled in code.
=> feat: re-enable welcome DMs and !mapadd

src/event-distribution/events/events.ts, src/event-distribution/events/timer.ts
Comment is moved `timer.ts` to the new event folder
=> Chore: Moved timer to the new event folder

src/event-distribution/command-decorator.ts, src/event-distribution/event-distribution.ts, src/event-distribution/events/events.ts, src/event-distribution/events/member-join.ts, src/event-distribution/types/base.ts, src/index.ts
Added event handler for member joining
=> Feat: support for member join events

src/programs/timeout-timer.ts, src/programs/timeout.ts
Im still pretty new at the event system, so if you got any comments don't be afraid to be harsh :)
=> Feat: timeout with timer support

src/programs/meta.ts
This one for you @adrian-goe 
Didn't know which emoji to use so I used the `:eeeh:` one, if our lovely Josh wants to create one for us he can go ahead!
=> Feat: add meta command

src/programs/timeout-timer.ts
I added reason into the error message, but I forgot I never implemented it, since it was a pain to do :)
=> Fix: TimeOut Timer has a feature that does not exist

src/events/message.ts, src/programs/deadchat.ts, src/programs/index.ts
Rewritten the command for deadchat.
=> Chore: Rewritten deadchat command

src/events/guild-member-update.ts, src/events/message.ts, src/programs/index.ts, src/programs/where-are-you-from.ts
Here is the `where-are-you-from` program using the new event handlers
=> Chore: Rewritten where-are-you-from.ts

src/collections/chat-names.ts, src/events/message.ts, src/programs/index.ts, src/programs/resources.ts
Rewritten `resources.ts` with the new event handlers
=> Chore: rewrite resources.ts

src/events/message.ts, src/programs/yestheory-content.ts
Rewritten with the new event handlers!
=> Chore: rewrite yestheory-content.ts

src/events/message.ts, src/events/reaction-add.ts, src/programs/index.ts, src/programs/polls.ts
I have rewritten `polls.ts` with the new event handlers but there was a function exported to the old event handler `reaction_add.ts` not sure what it really does or if I did it correctly since i left the emoji string empty.
=> Chore: Rewrite polls

src/events/message.ts, src/programs/dm-menu.ts, src/programs/index.ts
I hate rebasing.
I was basically stuck in a loop, it kept rebasing between the old commits of `polls.ts` and new ones.
=> Chore: refactor dm-menu.ts

src/events/guild-member-update.ts, src/programs/index.ts, src/programs/separators.ts
=> Chore: refactore separator.ts

.env.example, environment.d.ts, src/common/custom-methods.ts, src/programs/someone-tag.ts, src/programs/topics.ts
Google Sheets API v3 which YesBot is currently using, has been shut down on August 2nd, causing `@someone` and `!topic` in philosophy to fail.
This PR introduces a common method to use to access the first column of a sheet when provided the sheet's ID which covers both usecases mentioned above.
=> fix: move to google sheets API v4

src/events/message.ts, src/programs/timeout.ts
=> Chore: refactore timeout.ts

src/events/message.ts, src/programs/index.ts, src/programs/profile.ts
=> Chore: Refactore profile command

src/events/message.ts, src/programs/index.ts, src/programs/someone-tag.ts
=> Chore: Refactor @someone

src/events/guild-member-update.ts, src/events/reaction-add.ts, src/events/ready.ts, src/programs/index.ts, src/programs/nitro-colors.ts
=> Chore: Refactored nitro-colors

__tests__/utils/country-role-finder.spec.ts, src/collections/countryRoles.json, src/collections/flagEmojis.ts, src/utils/country-role-finder.ts
Hopefully, I didn't miss a file.
!closes #469
=> Fix: Added 2 new flags

src/programs/role/react-role-add.ts
The only way I thought of approaching this without having multiple `if` inside each other.
My creativity is sometimes frightening 
!closes #479
=> Chore: Re-added optional options to !role add

src/events/message.ts, src/programs/custom-messages.ts
=> Chore: Refactored feature request tally

.env.example, environment.d.ts, package.json, src/programs/activity/controller/activity-tracker.ts, src/programs/activity/types/update-activity.type.ts, src/programs/activity/usecase/update-activity.ts, src/programs/channel-toggle/handle-channelToggle-event.ts, yarn.lock
track server activity time for users
depends on
https://github.com/Yes-Theory-Fam/database/pull/66
=> feat(currency): track activity

package.json, src/index.ts, src/load-cron.ts, src/programs/activity/controller/activity-clean.cron.ts, src/programs/activity/controller/activity-tracker.ts, src/programs/activity/usecase/cleanup-activity.ts, src/programs/activity/usecase/update-activity.ts, yarn.lock
activity will be converted into currency
depends on https://github.com/Yes-Theory-Fam/database/pull/67 and https://github.com/Yes-Theory-Fam/yesbot-ts/pull/514
=> Introduce currency

src/programs/custom-messages.ts
https://discord.com/channels/449984633342525462/449984633908625409/894315708937285664
You can find the suggestions here :)
=> Feat: Add more random replies

.github/workflows/build.yml
=> feat: implement build action on PRs

src/programs/tickets/travel/common.ts
=> feat: reduce travel spam

src/index.ts
Currently, DM messages are not picked up by the bot due to a missing partial this should fix it
=> Fix: Added channel to partials

.renovaterc.json
This PR attempts to upgrade the renovate config to also support our database package.
=> chore: upgrade renovate config

src/programs/tickets/travel/common.ts
This PR addresses the issue of `!travel` crashing before completing through the following points:  
- Fixed error logging so errors that aren't too many retries are logged
- Filter for roles actually existing for resolved countries to avoid null-ish values
- Made error for no countries found a little more specific
Closes #591
=> fix: travel crashes without error

environment.d.ts, src/log.ts, src/programs/activity/controller/activity-clean.cron.ts, src/programs/activity/usecase/cleanup-activity.ts, src/programs/timer/timer.service.ts
This PR aims to make the bot more stable by
1) Fixing a bug causing the bot to attempt the same entry twice, causing an uncaught prisma exception
2) Reducing the heavy logging by the activity cron to loglevel debug and allowing setting the log level from the env
=> Fix crashes, easy production debugging

.github/workflows/build.yml, .github/workflows/linting.yml, .github/workflows/test.yml
=> Upgrade Node in GitHub Workflows

__tests__/mocks/guild.ts, __tests__/mocks/guildmember.ts, __tests__/mocks/index.ts, __tests__/mocks/message.ts, __tests__/mocks/reaction.ts
=> chore: move mocks to reflect construct

src/programs/daily-challenge.ts, src/programs/yestheory-content.ts
After having the bot run self-pings countless times I could not reproduce the problem locally. It was suggested in the past to group the embed and ping message together and it certainly won't harm so let's try that then.
=> fix automated group pings (maybe)

src/programs/tickets/travel/approve-ticket.ts
=> fix: travel title being too long

src/programs/tickets/travel/approve-ticket.ts
=> fix: travel ticket fails when adding members

src/programs/birthday-manager.ts
=> feat: easier birthday output

src/programs/daily-challenge.ts, src/programs/yestheory-content.ts
=> added 1s delay to auto ping

src/common/tools.ts, src/programs/daily-challenge.ts, src/programs/group-manager/user-commands/group-ping.ts, src/programs/yestheory-content.ts
=> Fix: Force ping needed groups

src/programs/group-manager/user-commands/group-search.ts
=> Fix: undefined in command !group search string results

src/common/tools.ts, src/programs/addvote.ts, src/programs/dm-menu.ts, src/programs/voice-on-demand.ts
There are still some instances where YesBot restarts on errors deleting messages so this PR adds some awaits and catch clauses in places where messages are deleted so it's not a problem if a user deletes their message faster than YesBot can.
=> Add some missing awaits and catch calls

package.json, src/event-distribution/event-distribution.ts
Including the test folder in compilation changed the index.js path and the path to the programs that are used to resolve commands so this PR fixes that.
=> fix: broken deployment

src/programs/tickets/travel/common.ts
=> feat: limit number of countries per travel ticket to 3

src/programs/birthday-manager.ts, src/programs/tickets/travel/open-travel-ticket.ts
- Update BB to slash commands
- Add clarification to !travel missing role error
Closes #785
=> Small stuff

src/programs/deadchat.ts, src/programs/profile.ts, src/programs/resources.ts, src/programs/send-video.ts
This PR converts `!deadchat`, `!profile`, `!resources` and `!video` to their respective slash commands.
=> feat: More slash commands! (`/deadchat`, `/profile`, `/resources`, `/video`)

src/programs/birthday-manager.ts
=> Replaced user mention with user id when generating two slash commands

src/programs/map.ts
=> fix: Allow USA members to add their location

environment.d.ts, src/index.ts, src/programs/birthday-manager.ts
- fix: serialization crash
- chore: replace deprecated builder
- fix: select staying despite error
=> Fix: serialization crash

src/event-distribution/event-distribution.ts, src/event-distribution/events/context-menu/build-context-menu-commands.ts, src/event-distribution/events/context-menu/common.ts, src/event-distribution/events/context-menu/context-menu-message.ts, src/event-distribution/events/context-menu/context-menu-user.ts, src/event-distribution/events/context-menu/index.ts, src/event-distribution/events/events.ts, src/event-distribution/events/slash-commands/slash-commands.ts, src/event-distribution/helper.ts, src/event-distribution/types/base.ts, src/event-distribution/types/hioc.ts, src/programs/addvote.ts, src/programs/meta.ts
- Add Support for User and Message Context Menu Commands
- Convert `!addvote` to Message Context Menu Command
- Convert `!meta` to Message Context Menu Command
=> feat: context menu comands

package.json, yarn.lock
=> fix: member names showing up wrong

src/programs/voice-on-demand/commands/voice-knock.ts
This PR attempts to implement issue #1031.
=> Feature: Ping knocker once they are let in

package.json, src/event-distribution/event-distribution.ts, src/index.ts, yarn.lock
=> chore: use tsx

src/programs/rate-limiter/rate-limiter.ts, src/programs/rate-limiter/spam-tracker.ts
Instead of just reporting the suspected spam in bot-development, we now issue a timeout on the offending member and delete the trail of messages that tripped the limit.
=> feat: harder anti-spam action
