Yes-Theory-Fam/yesbot-ts

- index.d.ts
- package-lock.json
- package.json
- src/common/tools.ts
- src/events/MemberJoin.ts
- src/events/ReactionAdd.ts
- src/events/ReactionRemove.ts
- src/programs/AdventureGame.ts
- src/programs/EasterEvent.ts
- src/programs/ExportManager.ts
- src/programs/GroupManager.ts
- src/programs/InitialiseTestEnvironment.ts
- src/programs/ProfileManager.ts
- src/programs/ReactRole.ts
- src/programs/Someone.ts
- src/programs/StateRoleFinder.ts
- src/programs/Ticket.ts
- src/programs/Unassigned.ts
- src/programs/WhereAreYouFromManager.ts
- tsconfig.json
Changed dependency discord.js from master to ^12.0.0
Updated tsconfig with include and exclude fields
Installed `@types/ws` for one TS error
Changed `.addBlankField()` to `.addField('\u200b', '\u200b')` (see https://discordjs.guide/popular-topics/embeds.html#using-the-richembedmessageembed-constructor)
Resolved all TS errors coming from the change to Managers from discord.js 11 to 12
Added index.d.ts to add typings for country-code-emoji
Ran `npm upgrade` to get all the fresh goodness (including TS 3.8)
--------------
`!group search` now displays a new form of embeds showing 4 groups and their descriptions at a time
Parameter to `!group search` is used to filter groups
Groups are ordered by member count (descending)
Embeds are sent with two reactions that can be used to flip through the …
> chore: TS Cleanup / feat: group search pages

- src/entities/Deadchat.ts
- src/programs/Deadchat.ts
This change would get rid of both deadchatQuestions.json and usedDeadchatQuestions.json by moving the storage of the questions and their used state to the database.
> feat: moved deadchat questions to database

- src/collections/flagEmojis.ts
The flag made from regional indicators U and M looks indentical to the US flag (see https://emojipedia.org/flag-us-outlying-islands/) which has caught plenty people from the US now.
This PR adds an entry to the flag emoji collection that lets the UM flag resolve to the US in the same way the actual US flag does.
> fix: UM flag didn't resolve to US (+ BV -> Norway)

- src/events/MessageManager.ts
- src/programs/Poll.ts
- src/programs/index.ts
Polls now detect options, falling back to A/B if neither of the two attempts to find intended options brought up at least two.
The first attempt consists of checking for emojis at the beginning of a line. All found emojis are added to the array of reactions and returned.
The second attempt looks for capital letters followed by punctuation (to avoid the start of the question for example). Letters are collected, converted to regional indicators and reacted with.
ToDo: In case someone tries to cheat the bot by using the same letter or reaction twice, an error will be thrown (couldn't do this yet because reply is messing around and I don't know why).
> feat: more flexible polls

- src/programs/Poll.ts
This fixes a bug where a certain way of creating a poll would lock up
the bot because of a bad regex.
After discussion, all emojis are now registered as potential option and
reacted with.
> fix: poll options for emojis

- src/collections/flagEmojis.ts
- src/programs/WhereAreYouFromManager.ts
Fixes this:
and reintroduces the flag overrides from `:flag_um:` to the US and `:flag_bv:` to Norway.
> fix: flag overrides breaking country by name

- src/programs/BirthdayManager.ts
Fixes a bug for people adding their birthday with a country role that starts with `I'm from the` (with the `the` being the issue):
> fix: timezone evaluation for countries starting with 'the'

- src/common/state.ts
- src/events/MessageManager.ts
- src/programs/WhereAreYouFromManager.ts
New handling for DMs to not treat everything as new nickname:
After 60 seconds either no reaction on the initial message or no message after being prompted for a name, the bot will remove all messages sent so far, leaving the user with this:
> feat: rename guard for DMs

- src/programs/BuddyProject.ts
Checking for date >= 15 will kill matching at the end of the month.
This commit requires `BUDDY_PROJECT_MATCHING `to be added to const.ts
> feat: feature toggle for buddy project matching

- src/events/MessageManager.ts
With the changes to groups, the demands for new channels with the groups ping enabled came up.
This PR enables the Gaming category as well as learning-spanish (after a spanish learning group was created).
> fix: allow group pings in the gaming category

- src/entities/UserGroup.ts
- src/programs/GroupManager.ts
Adds new behaviour for group pings. By default all groups will receive a cooldown of 60 minutes, this can be changed per group using a new command.
Block in action:
The message about the cooldown is removed after 10 seconds.
The PR also adds a new command for mods:
`!group changeCooldown <groupname> <newCooldown>`
will update the cooldown for a group. Example:
`!group changeCooldown CoStar 5`
The behaviour of `!group create` remains unchanged. When a new group is to be created with a cooldown other than 60 minutes, it requires a second command for now.
> feat: cooldowns for group pings

- src/programs/GroupManager.ts
Fixes a bug where this would fail to find the correct group:
```
@group something
This is something amazing
```
Because the split was exclusively done on spaces and not on whitespace.
This PR fixes that behaviour (top is before the fix, bottom with the fix):
> fix: a group ping followed by a newline doesn't work

- src/events/GuildMemberUpdate.ts
When a guild user is changed, this checks for a change of roles from a general role to a more specific region role.
In case such a change happened, the more general role is removed.
This can be coupled with the role assigning reactions to create a more automated region assigning.
> feat: remove general country roles when region is added

- src/events/MessageManager.ts
While I wasn't able to reproduce the issue locally, this sometimes happened:
Adding a filter to exclude bot messages in the DMs should hopefully fix this.
> fix: bot message was sometimes seen as name request

- src/programs/GroupManager.ts
I *think* this works, in tests it looks good but it is 4 in the morning and I'd be happy if someone could double check this.
Background: It happens that messages are quotes that contain a group ping. Those shouldn't cause a new group ping:
This PR (somewhat lazily) fixes this by checking if there is any group ping outside quotes. That still allows this behaviour (the first one actually tries to ping group thisfails instead of something):
But that is a problem for another PR, I guess.
> fix: ignore group pings that are in a blockquote

- src/events/MessageManager.ts
Quick win: When you are not on the server and DM the bot, you are greeted with a short message informing you that you are not on the server including a link to it.
This guards against people who are not on the server, who could attempt to change their name, leading to the bot trying to call `setNickname` on an undefined object (if I am not mistaken).
> feat: guard against dms from non-members

- src/programs/BirthdayManager.ts
Adds another timezone override.
The timezones library has CZ stored as Czechia while the server has it as Czech Republic so we have to work around that.
> fix: birthday timezones for czech republic

- src/programs/BirthdayManager.ts
Argentina has a lot of listed timezones, only one of which seems relevant however. Added override for that because some of the list broke the bot.
> fix: Override for Argentina Timezones

- src/programs/BuddyProjectGhost.ts
I accidentally made it so that people only have to be matched for three days before being able to report themselves as ghosted. That should have remained at one week. The three days were only the timespan between report and getting a new buddy.
> fix: durations in buddy project ghost process

- src/events/MessageManager.ts
Because messages were only split on spaces, using a group ping immediately after a linebreak would leave the entry in the words array as `something\n@group`.
This PR changes splitting to whitespace in general.
> fix: broken group ping when used immediately after a linebreak

- src/common/state.ts
- src/events/Ready.ts
- src/programs/VoiceOnDemand.ts
- Cleans up empty channels if they went empty during a restart
- No duplicate timeouts per channel that made them get deleted one minute after the last person left
(Last person leaves, comes back after 50 seconds, leaves 5 seconds later, channel was deleted 5 seconds after that)
- No pinging the Yes Theory role anymore when someone uses it without the role (that could have been a lot of fun)
- Changed max limit from 10 to 30
- False command calls and error messages are properly cleaned up
- Simplified permissions
> finishing touches to voice on demand remake

- src/programs/GroupManager.ts
- src/programs/Someone.ts
This PR removes logging in two positions that are frequently hit and serve no purpose anymore. Thus the only thing the logs are doing are clutter the output of journalctl and can be removed.
> chore: remove irrelevant logging

- src/events/GuildMemberUpdate.ts
By force fetching the channel's messages, we can avoid them being undefined in the loop over the reactions
> fix: error when resolving channel permissions

- src/events/GuildMemberUpdate.ts
- src/events/ReactionAdd.ts
- src/events/Ready.ts
- src/programs/NitroColors.ts
- src/programs/ReactRole.ts
- src/programs/index.ts
This PR aimed to allow supports selection of a nitro color. To make testing possible without changing a bunch of hardcoded IDs in several places, the logic handling nitro color selection was first refactored to determine the entities defined by the hardcoded IDs more dynamically.
The message that people can select their color from is not defined by an ID anymore but instead as the first message in the pick-your-color channel.
The nitro roles are not defined by IDs anymore but as any role mentioned in the first message in the pick-your-color channel.
- chore: refactor nitro color handling
- feat: allow supports selection of a nitro color
> Allow Supports selection of Nitro colors

- src/programs/Someone.ts
To reproduce the error on master, try using at-someone without the Seek Discomfort role or twice on the same day. In both cases, `Tools#handleUserError` is used to delete the message and display an error message. Deleting the message is already done in the top of the someone code so I moved it down to avoid this.
> fix: error about unkown (deleted) message

- src/programs/NitroColors.ts
Because of a second message in the selection channel, one condition required for checking whether someone already has a nitro color was always false because `message.fetch({ limit: 1 });` gets the last message, not the first. This PR fixes this by fetching the last 10 messages, reversing the order and taking the first of those to get the first message of the channel (as long as there is a max of 10 messages in the channel that is).
> fix: multiple nitrocolor selection

- src/events/GuildMemberUpdate.ts
I accidentally set all permissions on the channel instead of overwriting a single one. This PR fixes this to prevent further [invasions of germany](https://cdn.discordapp.com/attachments/450163655452131328/758080174683062312/unknown.png) by just creating a single overwrite instead of resetting everything.
> fix: full overwrite of permissions when break role is given

- src/programs/VoiceOnDemand.ts
Voice channels were previously created with just owners being able to join. The permission overwrites to prevent Time Out from connecting and Break from seeing were added only after the owner joined. Both permissions are now set when the room is initially created.
> fix: time of setting timeout and break permission on !voice channels

- src/programs/VoiceOnDemand.ts
- mitigated two errors caused by nulled values through discord.js
- allowed to select an emoji before all are reacted with by the bot
- don't delete the request to claim ownership (mostly as proof)
- don't delete the voice channel; instead select a random member in the voice channel as the new owner
> fix: a few errors and things in !voice

- src/events/GuildMemberUpdate.ts
- tsconfig.json
This is an attempt to fix an issue where reactions are not properly resolved due to API limitations.
Currently to check whether the user has reacted on a certain message with a certain emoji, the message including reactions is fetched, then for each emoji the users are fetched. The API caps this at a limit of 100 users being fetched which isn't enough for the close to 1000 reactions on the most reacted message of the server.
Because the before and after parameters of fetch are connected with *or* and not with *and* using both before and after causes the exact same result.
This PR attempts to use after with a Snowflake close to the one of the users ID (using the new ES2020 BigInts to subtract 5 from their ID). If the IDs that are fetched are sorted ascending, the snowflake fo the user …
> fix: non resolving permissions

- src/events/MemberJoin.ts
- src/events/MessageManager.ts
- src/programs/Unassigned.ts
- src/programs/WhereAreYouFromManager.ts
- src/programs/index.ts
This PR creates the base for the future slow transition to all users without country role having the Unassigned role. This update is mandatory before starting to "migrate" old users to ensure that only one pass over all users is required (hopefully... fingers crossed).
> feat: Unassigned role on entrance, removed on country role

- src/events/GuildMemberUpdate.ts
This is to reduce the overhead of the bot adding and removing a bunch of roles both in normal operation as well as during the migration to the Unassigned role.
> fix: ignore Unassigned role when handling seperators

- src/programs/VoiceOnDemand.ts
Self explanatory name, changed the prompt when owner leaves their custom voice channel to say it'll pick a new owner at random instead of it'll delete the channel.
> Updated prompt - owner left

- src/events/MessageManager.ts
self explanatory name
if message contains oo, bot will react with ghost 30% of the time
> set chances of ghost appearing to 30%

- src/programs/PollsManager.ts
This fixes a rare edge case when a mod has to delete previous reactions and add them again later. For some reason the count property of the freshly fetched and updated reaction object contains the wrong value in the following scenario
1. Add the reaction
2. Bot reacts properly
3. Clear that reaction from all users
4. Add the reaction again
5. reaction#count is 2 instead of 1
The code now doesn't fetch the reaction but the users and uses the size of that collection to determine whether something was the first reaction of a kind or not.
> fix: broken poll reactions for deleted reactions

- src/events/ReactionAdd.ts
For some reason guildMember is null in extremely rare cases and I don't know why so we just provide a proper error message until it's figured out.
> fix: Proper message when member is null

- src/events/MessageManager.ts
- src/programs/TemplateMode.ts
- src/programs/index.ts
Adds a new command that allows switching channel permissions of start-here and flag-drop to "Template Mode" that allows creating a server template.
This is done by switching to a different set of permissions that shows and hides the channels for the same people but that allows creating a server template through the use of less permission overwrites when required.
That setup however causes several Server Discovery features to fail so it should not be active when not required.
`!templateMode on` Changes the permissions to a set that allows creating a server template (takes a few seconds)
`!templateMode off` Changes the permissions to a set that allows use of Server Discovery (takes around 5 minutes to complete)
> feat: template-mode

- src/programs/SendFromDB.ts
Because the bot saves challenges as used at 00:00 of the day they were posted but they are posted with 8 hours offset, they is no challenge in the 8 hours before a new one is posted.
This is now mitigated by doing a comparison with the datetime 2 days and 8 hours back and taking the (hopefully only) one challenge that has a last_used date after that.
> fix: there not being a challenge 8 hours before a new one

- src/programs/PollsManager.ts
In two edge cases the bot wasn't able to properly add reactions:
- Numbers at the start of a line; since :one: is built in unicode as `1<some invisible character>`, digits have to match `\p{Emoji}` used in the regex to detect unicode emojis. This is fixed by filtering out single digit "emojis".
- Emojis with a strange additional character after them. For some reason, some emojis sent in polls were sent with a character with codepoint 65039 causing Discord to reject the reaction. Dirty but working fix is to split emojis sent, filtering out the character with the problematic codepoint, joining the pieces and using that cleaned up version.
> fix: polls breaking with numbers and certain emojis

- src/programs/VoiceOnDemand.ts
Added the .first() at the end because it returned a collective string and that was big red everywhere
This was only tested with 3 accounts A and B in the voice channel and C not in the voice channel trying to claim
When A (Host left) C clicked on the claim message but once pressed by B it was given to B :)
Quick warning: With such a small testing team which is me and my other accounts that I call friends. I have no idea how this will work if there are multiple in the voice channel. 
But going off logic here seems okay?
> fixed bug #214

- src/games/GameHub.ts
- src/games/GameSession.ts
- src/games/spyfall/Spyfall.ts
- src/programs/GroupManager.ts
The reason for this bug was because the bot is not able to send to the player a dm if they have it disabled in their privacy settings, it generated a bunch of errors in the log making a non-ending session.
Testing:
4 accounts to launch the game. 
- First Test: One account had their privacy disabled the bot send a message in #bot-games text channel saying the game couldn't start because of @{PLAYER WHO HAS "ALLOW DIRECT MESSAGES FROM SERVER MEMBERS" DISABLED} and wouldn't launch the game. Trying to open another game session immediately generated no bugs and also didn't allow the game to start.
- Second Test: All users had the right settings game launched with no issue, all commands work normally, the game runs with configurations being changeable. Tbh idk what I missed but doesn't feel …
> Fixes for issue #222 and issue #223

- src/games/GameHub.ts
- src/games/GameSession.ts
- src/games/spyfall/Spyfall.ts
Testing:
Tested users currently in a game and if they can be invited by user C, the double-check for issue #223 basically
Tested users cannot be invited to a new game if on the configuration page
Implementation:
In file: GameHub.ts, added the if to check if cleanPlayers is bigger or equal to the minimum of players required before starting the game.
In these files: GameHub.ts, GameSession.ts, and Spyfall.ts. Added the new property called Configuration. Basically split the patch config to avoid users being invited to a new game while on the configuration page of the game.
> fix: issue #223

- src/entities/Birthday.ts
- src/entities/Deadchat.ts
- src/entities/Someone.ts
- src/entities/UserGroup.ts
- src/events/MemberLeave.ts
- src/programs/BirthdayManager.ts
- src/programs/Deadchat.ts
- src/programs/GroupManager.ts
- src/programs/ProfileManager.ts
- src/programs/Someone.ts
Resolves _parts of_ #189.
I think the rest can follow suit, but I am not sure how to test that it all works. These changes worked out the box based on the implementation description you gave in #189, so I think that will be the case for the remaining entities too.
Merging this unblocks #205.
> Convert database entities from TypeORM Repositories to extending BaseEntity

- package-lock.json
- package.json
- src/db.ts
- src/events/Ready.ts
- src/index.ts
- src/log.ts
- src/programs/BuddyProject.ts
- src/programs/DailyChallenge.ts
- src/programs/GroupManager.ts
- src/programs/NitroColors.ts
- src/programs/ReactRole.ts
- src/programs/Valentine.ts
Add logging using [Winston](https://github.com/winstonjs/winston).
Example output:
```
$ npm start
> tsbot@1.0.0 start
> ts-node-dev --respawn src/index.ts
Using ts-node version 8.10.2, typescript version 4.2.4
info [main] [index]: Starting YesBot
debug [main] [index]: Logging in to Discord Gateway
info [db] [init]: Database connection established.
info [events] [Ready]: Bot is online - bot-name#1337
debug [events] [Ready]: Finding guild based on GUILD_ID {"GUILD_ID":"MYGUILDID"}
warn [programs] [NitroColors]: Didn't find a message in #pick-your-color to load Nitro colors from. Skipping setting up nitro colors
```
When run in a TTY, it will enable colours and some simple timestamps:
And if not, colours are disabled and the timestamp is hidden. I chose to hide the timestamp too because I …
> Add logging using Winston

- src/events/GuildMemberUpdate.ts
- src/events/MessageManager.ts
- src/programs/WhereAreYouFromManager.ts
- src/programs/index.ts
- src/scripts/memberMigration.ts
This PR implements support for a new member role. The plan is to move away from an non-member role (currently Unassigned) and instead have a common role for all members of the server who have dropped their flag and selected their region to clean up permissions and make creating new server templates a lot easier.
- Updated the old unassignedMigration script to do the opposite of its original purpose. When run, it will add the Member role to each member encountered that has a role starting with "I'm from". Other members will remain untouched.
- Updated WhereAreYouFromManager to add the role on flag-drop. Since permissions will eventually be tied to the role, it should only be given out when a region is selected to reflect the current behaviour. Since that equals the desired behaviour for …
> feat: new member role and #147

- .renovaterc.json
add lockFileMaintenance so that renovate also updates package-lock
this is necessary because we have npm ci in the ci pipline
> add lockFileMaintenance so that renovate also updates package-lock

- .renovaterc.json
jest and ts-jest are both attempted to be updated (see #279 and #280 respectively) but require the other to be updated with them.
This PR groups them so renovate updates them together.
> fix: group jest packages in renovate

- __tests__/utils/country-role-finder.spec.ts
- src/programs/where-are-you-from.ts
- src/utils/country-role-finder.ts
This PR closes #306 and reintroduces previously broken flag overrides. They broke since the emojis now also play a relevant role. Thus a small record was introduced to keep overrides of the emojis to resolve the correct role in case lookalike flags (:flag_ea: vs :flag_es: for example) are used.
> fix: broken flag overrides and regional roles being assigned

- src/programs/group-manager.ts
We do not want the YesTheoryUploads group to be pinged by all members, just by the bot (ignoring even supports and admins for now).
Until #320 is closed, a little string comparison shall do the trick.
> fix: disable group YesTheoryUploads for members

- src/programs/birthday-manager.ts
The bot previously used the year 1970 to return the date so feb 29th automatically rolled over to march 1st. Instead we can use year 1972 which was a leapyear to return and save the date.
> #325 fix: accept feb-29th as birthday

- __tests__/event-distribution/events/__snapshots__/guild-member-update.spec.ts.snap
- __tests__/event-distribution/events/guild-member-update.spec.ts
- src/event-distribution/README.md
- src/event-distribution/command-decorator.ts
- src/event-distribution/event-distribution.ts
- src/event-distribution/events/events.ts
- src/event-distribution/events/guild-member-update.ts
- src/event-distribution/types/base.ts
- src/event-distribution/util.ts
- src/index.ts
- src/programs/decorator-test.ts
This PR adds support for the GuildMemberUpdate event to the new event distribution system.
I have absolutely no idea how to get sensible tests to work. My attempts are commented out in `__tests__/event-distribution/events/guild-member-update.spec.ts` but all failed due to some weird stuff inside Discord.JS (pretty much all interactions with roles and GuildMembers rely on accessing the member's roles which in turn requires accessing the everyone role of the guild). I don't know how to mock that, unfortunately; help is appreciated!
> feat: Add GuildMemberUpdate to event distribution

- src/programs/yestheory-content.ts
If webhooks count as bots this should not return an error and we should no longer need to use `hasRole`.
Used the test YesBot by forcing it to send a message in #yestheory-uploaded which pinged the group.
> fixed yestheoryuploaded ping

- src/programs/map.ts
- src/programs/where-are-you-from.ts
This PR disables !mapadd and removes the DM sent in where-are-you-from as reaction to the bot quarantine. These two changes had previously only been on the server and never ended up in the codebase so this should be fixed now that the bot is deployed through docker.
> fix: disables DM functionalities due to bot quarantine

- src/collections/flagEmojis.ts
Removed EU role from `flagEmojis.ts`
> Chore: Removed EU role

- src/event-distribution/event-distribution.ts
There is a case where the initialize promise is neither resolved nor rejected. This PR fixes that.
> fix: reject the loading promise on glob error

- src/programs/release-notes/usecase/github-release-notes.usecase.ts
Just to be sure it works as expected, in case a library would decide to change its default ordering, or the table would, or anything else.
> Specify the ordering of database select for release notes

- CONTRIBUTING.md
The setup guide for YesBot didn't mention migrating or pushing the schema to the DB yet.
This PR includes an additional step in the contributing guide to mention that required command. It also fixes a small left-over phrase that wasn't accurate anymore.
> chore: update contributing to mention db migration

- __tests__/utils/country-role-finder.spec.ts
- src/programs/where-are-you-from.ts
- src/utils/country-role-finder.ts
This should close #382, the way emojis are on discord is combining multiple emojis together (does this even make sense..?). The current regex splits them up separately, combines the first 2 indexes and the last 2 in the array, which together will give the first 2 flags send. If they are different, the bot replies with the message. This kind of can be bypassed by sending the same flag twice then a different one but either way he will still get assigned the role of the first flag detected, but the bug was mostly having the same flag twice and it gets detected as different, so that doesn't really matter.
> Fix: detect multiple flags

- __tests__/event-distribution/events/__snapshots__/message.spec.ts.snap
- __tests__/event-distribution/events/__snapshots__/reactions.spec.ts.snap
- __tests__/event-distribution/events/message.spec.ts
- __tests__/event-distribution/events/reactions.spec.ts
- src/event-distribution/README.md
- src/event-distribution/command-decorator.ts
- src/event-distribution/event-distribution.ts
- src/event-distribution/types/base.ts
- src/programs/decorator-test.ts
- src/programs/polls.ts
- src/programs/timeout-timer.ts
Requiring all roles in the requiredRoles array to be present was a bad idea; requiring only one makes so much more sense in our usecases.
This PR renames requiredRoles to allowedRoles and fixes the issue described above.
> fix: require only one role in requiredRoles

- src/event-distribution/event-distribution.ts
Array.some returns false if the array is of zero length. In our usecase an empty array should indicate that everyone may use it, however. This PR fixes the behaviour of allowedRoles.
> fix: allowed-roles

- package.json
- yarn.lock
countries-and-timezones@3.2.x breaks TypeScript compilation.
This PR downgrades the dependency to 3.1.0 to make the build work.
> fix: downgrade countries-and-timezones

- src/programs/timeout-evasion.ts
In case the bot was down and a user was forgiven this should clean it up on ready, so they dont get the the role assigned to them when they rejoin the server.
!closes #474
> Fix: Added DB cleanup and disconnect users who are timed out

- src/programs/release-notes/usecase/github-release-notes.usecase.ts
Closes #570
Naively implemented as "Any tag with 3 segments separated by dots with anything but a 0 as last segment is a patch release"
> feat: disable updates for patch versions

- src/event-distribution/events/events.ts
Took longer than expected sorry, anyways `refuseWithMessage` was already awaited when called, so I'm assuming you forgot to add `async` to it, should work as intended.
!closes #590
> Feat: Use handleUserError for event user errors

- src/programs/dm-menu.ts
Added an await and threw the error to the bot-output so moderators see the reason why it was denied
> Fix: avoid crashing bot on incorrect nickname format

- __tests__/event-distribution/events/__snapshots__/member-leave.spec.ts.snap
- __tests__/event-distribution/events/__snapshots__/message.spec.ts.snap
- __tests__/event-distribution/events/__snapshots__/reactions.spec.ts.snap
- __tests__/mocks/guild.ts
- __tests__/mocks/guildmember.ts
- __tests__/mocks/index.ts
- __tests__/mocks/message.ts
- __tests__/mocks/reaction.ts
discord.js 13.2.0 included a commit that marked all discord.js classes' constructor private. There is an existing issue talking about this although it was closed by its author here: https://github.com/discordjs/discord.js/issues/6798
Since we depend on those constructors for our mocks/test fixtures, I marked all their use with `@ts-expect-error` so we can start updating discord.js again. Doesn't make me happy to do it this way but I don't see any other approach, honestly.
1) This branch merges into the renovate update branch! When merging this, please also merge #533 along with it (only when the pipeline goes green of course!).
2) Since this doesn't merge into master, there are no Actions running on this; I ran this locally and it worked but double checking would be good.
> fix: discord.js test typescript

- src/events/message.ts
Currently a missing `break;` causes !group commands to be executed twice in permanent-testing. This PR reintroduces it.
> fix: double group command execution

- src/programs/birthday-manager.ts
A recent update of countries-and-timezones updated the timezone data which deprecated Canada/-prefixed timezones. This PR adds the deprecated option to restore old behaviour.
The bot now further automatically pings Developers in case no timezones were found for a member to not have them wonder what happened and instead push that fate onto the Developers.
> fix: canada timezones being empty

- src/programs/tickets/travel/common.ts
This fixes an issue with `!travel` causing missing details to kill the travel request entirely without any feedback to the member.
> fix: onFailure being called despite undefined

- src/programs/tickets/travel/decline-ticket.ts
This PR attempts to fix an issue with messages not being present in cache when declining a travel ticket by force fetching them.
> fix: avoid null message for reaction

- src/programs/voice-on-demand.ts
Some users would `!voice limit 2` in a channel of 5 members in case someone disconnects and to avoid losing his place or getting a random. But this generates a bug where `!voice up` or accepting a `!voice knock` would just up one to the channel limit.
> Channel members: 5
Channel limit: 2
Do a `!voice up`
Expectations: Channel limit: 6
Results: Channel limit: 3
> Fix: Voice up and down limits vc to current members +1 

- src/index.ts
This could be a possible fix for #736 since we have two `ready.ts` that handle the bot ready event, we can make the old event take resolving the guild before heading to the new event distribution system. I'm assuming that when you said color selection, you meant the nitro colors since they use the new `ready.ts` loading the old one first doesn't seem like a lousy idea 🤔 
Hopefully !closes #736
> Fix: race condition

- src/programs/tickets/common.ts
The current code creates channel names with multiple dashes which Discord automatically collapses to a single one causing channels not to be found anymore.
> fix: channels not being found with multiple spaces

- src/programs/group-manager/group-service.ts
- fix: `UNKNOWN_ERROR`  which prevented the user from joining any group if they were not enrolled in at least one group.
> fix: `UNKNOWN_ERROR` when a member is not in any group

- src/common/tools.ts
The check to see if a command was enabled was including the Support role, which is default enabled for all commands on the production server.
> fix: command check

- prisma/schema.prisma
Fixes a bug that showed up in sentry by replacing a custom unique constraint with a more direct unique constraint on the field itself
> fix: lookup-voice-by-channel

- src/log.ts
`util.inspect` prevents circular dependencies from breaking JSON serialization. The previous implementation caused error logging to crash the bot entirely in case the error contained any circular dependencies as is often the case with HTTP Request / Response objects.
> fix: prevent crash from circular references in errors

- src/programs/tickets/common.ts
If both
- A user already had a ticket open *and*
- They had their DMs locked down
The bot would crash due to a missing `await` and thus uncaught promise rejection.
> fix: uncaught promise crash in !travel

- src/programs/tickets/travel/travel-data-message-converter.ts
A mistake in the regex caused the message parser to ignore everything but the first line of the activities. This PR fixes that behaviour.
> fix: modern travel truncates activities

- src/programs/custom-messages.ts
Since YesBot is usually asked "Yes / No" questions, this response often didn't make sense (e.g. "Does X love me?" - "Just do it"). Thus it's been removed.
> fix: remove bad response

- src/programs/break-role/break-role-added.ts
- src/programs/break-role/break-role-removed.ts
Due to permission changes, the Break role (ironically) broke. To fix, we make adding the Break role remove the Member role and removing the Break role re-add the Member role.
> fix: break role

- .env.example
That line apparently made the setup fail
> chore: remove problematic line from .env.example
